# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- feature/*

pool:
  vmImage: ubuntu-latest

steps:

#Enable gitcommands using this account
- checkout: self
  persistCredentials: true
  fetchDepth: 0

#Config gitversion 5.12.x
- task: gitversion/setup@0
  displayName: 'Setup git version'
  inputs:
    versionSpec: '5.x.x'

#calculate the version of source code
- task: gitversion/execute@0
  displayName: 'Calculate SemVer'
  
  

#print in console current ersion
- script: echo current version is $(GitVersion.SemVer)
  displayName: 'Display calculated version'

#setting git user
- task: CmdLine@2
  displayName: Init git global config
  inputs:
    script: |
        git config --global user.email "EMAIL-OF-PIPELINE-USER"
        git config --global user.name "Pipeline"

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package  deploy:deploy-file'      
    mavenAuthenticateFeed: true
    options: '-X -P azure_artifacts -Dpackaging="jar" -DrepositoryId="Librerias_Prueba" -Durl="https://pkgs.dev.azure.com/greg8408/4cd26484-9ffc-4364-b77c-6bcd71cd4bc7/_packaging/Librerias_Prueba/maven/v1" -DgroupId="com.digitalthinking" -DartifactId="common-library" -Dversion="$(GitVersion.SemVer)" -Dfile="$(System.DefaultWorkingDirectory)/target/common-library-0.0.1-SNAPSHOT.jar"'




